### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [34]:
# Dependencies and Setup
import pandas as pd
import seaborn as sns

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Player Count

* Display the total number of players

In [35]:
# Total number of players by screen names
total_p = pd.DataFrame({"total players": [len(purchase_data["SN"].unique())]})

# Output
total_p

   total players
0            576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [36]:
# Total number of unique items ids calculation 179
unique_numbers = len(purchase_data["Item ID"].unique())
print(unique_numbers)

# Total number of in game purchases calculation 780
igp = purchase_data["Price"].count()
print(igp)

# Total revenue calculation 2379.77 
total_rev = purchase_data["Price"].sum()
print(total_rev)

# Average price calculation 3.05
avg_price = total_rev / igp
print(avg_price)

# New summary dataframe
summary_data = pd.DataFrame({
    'Number of Unique Items': [unique_numbers],
    'In Game Purchases': [igp],
    'Average Price': [avg_price],
    'Total Revenue': [total_rev]
})

# Cleaning up the data with formating and styling http://localhost:8888/notebooks/pandas-challenge/HeroesOfPymoli/HeroesOfPymoli_starter.ipynb#
summary_data['Average Price'] = summary_data['Average Price'].map('${:.2f}'.format)
summary_data['Total Revenue'] = summary_data['Total Revenue'].map('${:,.2f}'.format)
summary_data.style.set_properties(**{'background-color': 'lightblue',
                                    'color': 'black',
                                    'text-align': 'center',
                                    'border-color': 'black',
                                    'border-width': '2px',
                                    'border-style': 'solid'})\
             .set_caption('Purchasing Analysis')

179
780
2379.77
3.0509871794871795

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [37]:
# The unique number of rows in SN calculation 576 
total_p = len(purchase_data['SN'].unique())
print(total_p)

grouped_players = purchase_data.groupby('Gender')['SN'].nunique()

# Make serires into dataframe
new_purchase_data = grouped_players.to_frame('Total Count')

# How the fuck do I combined you!!!!!
new_purchase_data['Percentage of Players'] = new_purchase_data/total_p*100


#Formating
new_purchase_data.style.format({'Total Count': '{:.0f}',
                                'Percentage of Players': '{:.2f}'})\
                        .set_properties(**{'background-color': 'beige',      
                                        'color': 'black',
                                        'text-align': 'center',
                                        'border-color': 'black',
                                        'border-width': '2px',
                                        'border-style': 'solid',})\
                        .set_caption('Gender Demographics')\
                        .highlight_max(subset=['Total Count','Percentage of Players'], color='lightgreen', axis=0)\
                        .highlight_min(subset=['Percentage of Players','Total Count'], color='salmon', axis=0)\



# still need Percentage of players as correct percentage. Ask Tutor!!!!

576


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [44]:
# Purchase count by grouping Gender and item ID
purchasing_count = purchase_data.groupby('Gender')['Item ID'].count()
print(purchasing_count)

# Purchase totals by grouping Gender and Price
purchasing_v = purchase_data.groupby('Gender')['Price'].sum()
print(purchasing_v)

# Make serires into dataframe
purch_analysis=purchasing_count.to_frame('Purchase Count')

# Purchase average calculation
purch_analysis['Average Purchase Price'] = purchasing_v/purchasing_count
print(purch_analysis)

# 
purch_analysis['Total Purchase Value'] = purchasing_v
print(purch_analysis)

purch_analysis['Avg Total Purchase per Person'] = purchasing_v/grouped_players

#Formating
purch_analysis.style.format({'Purchase Count': '{:.0f}',
                                'Average Purchase Price': '${:.2f}',
                                'Total Purchase Value': '${:.2f}',
                                'Avg Total Purchase per Person': '${:.2f}'})\
                        .set_properties(**{'background-color': 'beige',      
                                        'color': 'black',
                                        'text-align': 'center',
                                        'border-color': 'black',
                                        'border-width': '2px',
                                        'border-style': 'solid',})\
                        .set_caption('Purchasing Analysis (Gender)')\
                        .highlight_max(subset=['Purchase Count',
                                               'Average Purchase Price',
                                               'Total Purchase Value',
                                               'Avg Total Purchase per Person'], color='lightgreen', axis=0)\
                        .highlight_min(subset=['Purchase Count',
                                               'Average Purchase Price',
                                               'Total Purchase Value',
                                               'Avg Total Purchase per Person'], color='salmon', axis=0)\

Gender
Female                   113
Male                     652
Other / Non-Disclosed     15
Name: Item ID, dtype: int64
Gender
Female                    361.94
Male                     1967.64
Other / Non-Disclosed      50.19
Name: Price, dtype: float64
                       Purchase Count  Average Purchase Price
Gender
Female                            113                3.203009
Male                              652                3.017853
Other / Non-Disclosed              15                3.346000
                       Purchase Count  Average Purchase Price  \
Gender
Female                            113                3.203009
Male                              652                3.017853
Other / Non-Disclosed              15                3.346000

                       Total Purchase Value
Gender
Female                               361.94
Male                                1967.64
Other / Non-Disclosed                 50.19

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [45]:
# Bins and labels 
bins = [0,9, 14, 19, 24, 29, 34, 39, 900]
bin_names = ["<10", "10-14", "15-19", "20-24", "25-29","30-34","35-39","40+"]

# bin the data based on age and calculate the percentages and write to a new dataframe
bin_age=pd.DataFrame((((pd.cut(purchase_data['Age'], bins, labels=bin_names)).value_counts())/total_p*100))

# Renaming the new dataframe column.
bin_age.rename(columns={'Age': 'Percentage of Players'},inplace = True)

# Total count based age
bin_age["Total Count"]=pd.cut(purchase_data["Age"], bins, labels=bin_names).value_counts()

#Formating
bin_age.style.format({'Total Count': '{:.0f}',
                    'Percentage of Players': "{:.0%}", })\
    .set_properties(**{'background-color': 'White',
                                    'color': 'black',
                                    'text-align': 'center',
                                    'border-color': 'black',
                                    'border-width': '2px',
                                    'border-style': 'solid'})\
                                    .bar(subset=['Total Count'], color='lightblue')\
                                    .bar(subset=['Percentage of Players'], color='lightgreen')\
                                    .highlight_min(subset=None, color='salmon', axis=0)\
                .set_caption('Age Demographics')

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [47]:
# Purchase to new dataframe
c_bin = purchase_data.copy()

# Values based on age
c_bin['Age']=pd.cut(purchase_data['Age'], bins, labels=bin_names)

# Calculate the total purchase count by age groups by counting the price rows for each group
V_bin = c_bin[['Price', 'Age']].groupby(['Age']).count()

# Rename
V_bin.rename(columns={'Price': 'Purchase Count'},inplace = True)

# Average purchase price by age groups
V_bin["Average Purchase Price"] = c_bin[['Price', 'Age']].groupby(['Age']).mean()

# Total purchase price by age groups by pricing for each group
V_bin['Total Purchase Price'] =c_bin[['Price', 'Age']].groupby(['Age']).sum()

#calculate the normalized totals for purchasing for each age group
V_bin['Normalized Totals'] = (V_bin['Total Purchase Price'] / bin_age['Total Count'])

#Formating
bin_3.style.format({'Purchase Count': '{:.0f}',
                                'Average Purchase Price': '${:.2f}',
                                'Total Purchase Value': '${:.2f}',
                                'Avg Total Purchase per Person': '${:.2f}'})\
                        .set_properties(**{'background-color': 'white',      
                                        'color': 'black',
                                        'text-align': 'center',
                                        'border-color': 'black',
                                        'border-width': '2px',
                                        'border-style': 'solid',})\
                        .background_gradient()\
                        .highlight_min(subset=None, color='salmon', axis=0)\
                        .set_caption('Purchasing Analysis (Age)')

NameError: name 'bin_3' is not defined

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [ ]:
 #  Id counts from purchase data for each SN
top_spenders = purchase_data['Item ID'].groupby(purchase_data['SN']).count()

# Created column in the Dataframe
top_spenders = pd.DataFrame(data = top_spenders)
top_spenders.columns = ['Purchase Count']

# The average purchase price per screen name
top_spenders['Average Purchase Price'] = purchase_data['Price'].groupby(purchase_data['SN']).mean()

# The total purchase price per screen name
top_spenders['Total Purchase Value'] = purchase_data['Price'].groupby(purchase_data['SN']).sum()

# Sort by descending order
top_spenders.sort_values(by=['Total Purchase Value'], ascending = False, inplace = True)

# Formating
top_spenders.head(10).style.format({'Purchase Count': '{:.0f}',
                                'Average Purchase Price': '${:.2f}',
                                'Total Purchase Value': '${:.2f}'})\
                        .set_properties(**{'background-color': 'white',      
                                        'color': 'black',
                                        'text-align': 'center',
                                        'border-color': 'black',
                                        'border-width': '2px',
                                        'border-style': 'solid',})\
                        .background_gradient()\
                        .highlight_min(subset=None, color='salmon', axis=0)\
                        .set_caption('Top Spenders')

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, average item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame